MunicipalServices/Controllers/CashiersChecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MunicipalServices.Data;

namespace MunicipalServices.Controllers
{
    [Authorize(Roles = "قسم المالية,الادارة")]
    public class CashiersChecksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Data.Users> usermanager;

        public CashiersChecksController(ApplicationDbContext context, UserManager<Data.Users> user)
        {
            _context = context;
            usermanager = user;
        }

        // GET: CashiersChecks
        public PartialViewResult Index(Guid id, bool IsCatchReceipts)
        {
            var model = _context.CashiersCheck.Include(u => u.User).AsQueryable();
            if (IsCatchReceipts)
            {
                model = model.Where(c => c.Deleted == false && c.CatchReceiptID == id);
            }
            else
            {
                model = model.Where(c => c.Deleted == false && c.ReceiptID == id);
            }
            return PartialView(model.OrderBy(c => c.CreatedDate));
        }

        // GET: CashiersChecks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cashiersCheck = await _context.CashiersCheck
                .Include(c => c.CatchReceipt)
                .Include(c => c.Receipt)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cashiersCheck == null)
            {
                return NotFound();
            }

            return View(cashiersCheck);
        }

        // GET: CashiersChecks/Create
        public IActionResult Create(Guid id, bool IsCatchReceipts)
        {
            var model = new Data.CashiersCheck();
            if (IsCatchReceipts)
            {
                model.CatchReceiptID = id; 
            }
            else
            {
                model.ReceiptID = id;
            }
            return View(model);
        }

        // POST: CashiersChecks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatchReceiptID,ReceiptID,CheckNumber,AccountNumber,CodeBank,BankName,CodeBranch,BranchName,DateOfTheWorthy,AmountOfMoney")] CashiersCheck cashiersCheck)
        {
            if (ModelState.IsValid)
            {
                var datetime = DateTime.UtcNow;
                cashiersCheck.ID = Guid.NewGuid();
                cashiersCheck.CreatedDate = datetime;
                cashiersCheck.UpdatedDate = datetime;
                cashiersCheck.UserID = usermanager.GetUserId(User);
                _context.Add(cashiersCheck);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                {
                    if (cashiersCheck.CatchReceiptID != null)
                    {
                        return RedirectToAction(nameof(Details), nameof(Data.CatchReceipts), new { id = cashiersCheck.CatchReceiptID });
                    }
                    else if (cashiersCheck.ReceiptID != null)
                    {
                        return RedirectToAction(nameof(Details), nameof(Data.Receipts), new { id = cashiersCheck.ReceiptID });
                    }
                    else
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View(cashiersCheck);
        }

        // GET: CashiersChecks/Edit/5
        public async Task<IActionResult> Edit(Guid? id, Guid? CheckReceiptID, bool IsCatchReceipts)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cashiersCheck = await _context.CashiersCheck.FindAsync(id);
            if (cashiersCheck == null)
            {
                return NotFound();
            }

            if (CheckReceiptID != null && CheckReceiptID != Guid.Empty)
            {
                if (IsCatchReceipts)
                {
                    cashiersCheck.CatchReceiptID = CheckReceiptID;
                }
                else
                {
                    cashiersCheck.ReceiptID = CheckReceiptID;
                }
            }
            return View(cashiersCheck);
        }

        // POST: CashiersChecks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,CatchReceiptID,ReceiptID,CheckNumber,AccountNumber,CodeBank,BankName,CodeBranch,BranchName,DateOfTheWorthy,AmountOfMoney,CreatedDate,UserID")] CashiersCheck cashiersCheck)
        {
            if (id != cashiersCheck.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    cashiersCheck.UpdatedDate = DateTime.UtcNow;
                    _context.Update(cashiersCheck);
                    var result = await _context.SaveChangesAsync();
                    if (result > 0)
                    {
                        if (cashiersCheck.CatchReceiptID != null)
                        {
                            return RedirectToAction(nameof(Details), nameof(Data.CatchReceipts), new { id = cashiersCheck.CatchReceiptID });
                        }
                        else if (cashiersCheck.ReceiptID != null)
                        {
                            return RedirectToAction(nameof(Details), nameof(Data.Receipts), new { id = cashiersCheck.ReceiptID });
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CashiersCheckExists(cashiersCheck.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cashiersCheck);
        }

        // GET: CashiersChecks/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cashiersCheck = await _context.CashiersCheck
                .Include(c => c.CatchReceipt)
                .Include(c => c.Receipt)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cashiersCheck == null)
            {
                return NotFound();
            }

            return View(cashiersCheck);
        }

        // POST: CashiersChecks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cashiersCheck = await _context.CashiersCheck.FindAsync(id);
            cashiersCheck.Deleted = true;
            _context.CashiersCheck.Update(cashiersCheck);
            var result = await _context.SaveChangesAsync();
            if (result > 0)
            {
                if (cashiersCheck.CatchReceiptID != null)
                {
                    return RedirectToAction(nameof(Details), nameof(Data.CatchReceipts), new { id = cashiersCheck.CatchReceiptID });
                }
                else if (cashiersCheck.ReceiptID != null)
                {
                    return RedirectToAction(nameof(Details), nameof(Data.Receipts), new { id = cashiersCheck.ReceiptID });
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool CashiersCheckExists(Guid id)
        {
            return _context.CashiersCheck.Any(e => e.ID == id);
        }
    }
}

MunicipalServices/Controllers/ReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MunicipalServices.Data;

namespace MunicipalServices.Controllers
{
    [Authorize(Roles = "قسم المالية,الادارة")]
    public class ReceiptsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<Data.Users> usermanager;

        public ReceiptsController(ApplicationDbContext context, Microsoft.AspNetCore.Identity.UserManager<Data.Users> user)
        {
            _context = context;
            usermanager = user;
        }

        // GET: Receipts
        public ViewResult Index()
        {
            var applicationDbContext = _context.Receipts.Include(r => r.User).Where(r => r.Deleted == false);
            return View(applicationDbContext);
        }

        // GET: Receipts/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipts = await _context.Receipts
                .Include(r => r.User).Include(c=>c.CashiersChecks)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (receipts == null)
            {
                return NotFound();
            }

            return View(receipts);
        }

        // GET: Receipts/Create
        public IActionResult Create()
        {
            ViewData["CurrencyType"] = new SelectList(from CurrencyType d in Enum.GetValues(typeof(CurrencyType)) select new { ID = (int)d, Name = Helper.Enumerations.GetEnumDescription(d) }, "ID", "Name");
            return View();
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FullName,AmountOfMoneyNumber,AmountOfMoneyText,Reason,OnAccount,ReceivedFrom,Currency,ID,CreatedDate,UpdatedDate,UserID,Deleted")] Receipts receipts)
        {
            if (ModelState.IsValid)
            {
                var datetime = DateTime.UtcNow;
                receipts.ID = Guid.NewGuid();
                receipts.CreatedDate = datetime;
                receipts.UpdatedDate = datetime;
                receipts.UserID = usermanager.GetUserId(User);
                _context.Add(receipts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(receipts);
        }

        // GET: Receipts/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipts = await _context.Receipts.FindAsync(id);
            if (receipts == null)
            {
                return NotFound();
            }
            ViewData["CurrencyType"] = new SelectList(from CurrencyType d in Enum.GetValues(typeof(CurrencyType)) select new { ID = (int)d, Name = Helper.Enumerations.GetEnumDescription(d) }, "ID", "Name");
            return View(receipts);
        }

        // POST: Receipts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("FullName,AmountOfMoneyNumber,AmountOfMoneyText,Reason,OnAccount,ReceivedFrom,Currency,ID,CreatedDate,UpdatedDate,UserID,Deleted")] Receipts receipts)
        {
            if (id != receipts.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    receipts.UpdatedDate = DateTime.UtcNow;
                    _context.Update(receipts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceiptsExists(receipts.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", receipts.UserID);
            return View(receipts);
        }

        // GET: Receipts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipts = await _context.Receipts
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (receipts == null)
            {
                return NotFound();
            }

            return View(receipts);
        }

        // POST: Receipts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var receipts = await _context.Receipts.FindAsync(id);
            receipts.Deleted = true;
            _context.Receipts.Update(receipts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReceiptsExists(Guid id)
        {
            return _context.Receipts.Any(e => e.ID == id);
        }
    }
}

MunicipalServices/Views/Receipts/Create.cshtml
@model MunicipalServices.Data.Receipts

@{
    ViewData["Title"] = "سندات الصرف";
}
<div class="roots-content-wrapper my-4 container-fluid dir-rtl" style="min-height:700px">

    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="content-box mt-2">
            <div class="content-box-header">
                <h3 class="content-box__title text-right">إضافة جديد</h3>
            </div>
            <div class="content-box-body">
                <div class="content-box-body__row row">
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="FullName" class="input-label text-right"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="AmountOfMoneyNumber" class="input-label text-right"></label>
                        <input asp-for="AmountOfMoneyNumber" class="form-control" />
                        <span asp-validation-for="AmountOfMoneyNumber" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="AmountOfMoneyText" class="input-label text-right"></label>
                        <input asp-for="AmountOfMoneyText" class="form-control" />
                        <span asp-validation-for="AmountOfMoneyText" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="Reason" class="input-label text-right"></label>
                        <input asp-for="Reason" class="form-control" />
                        <span asp-validation-for="Reason" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="OnAccount" class="input-label text-right"></label>
                        <input asp-for="OnAccount" class="form-control" />
                        <span asp-validation-for="OnAccount" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="ReceivedFrom" class="input-label text-right"></label>
                        <input asp-for="ReceivedFrom" class="form-control" />
                        <span asp-validation-for="ReceivedFrom" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="Currency" class="input-label text-right"></label>
                        <select asp-for="Currency" asp-items="ViewBag.CurrencyType" class="form-control"></select>
                        <span asp-validation-for="Currency" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="root-space__btn-wrapp col-12">
                <a asp-action="Index" class="roots-btn btn btn-secondary ml-3">إلغاء</a>
                <button type="submit" class="roots-btn btn btn-primary roots-btn-w-plus">إضافة</button>
            </div>
            <br />
        </div>
    </form>
        </div>

MunicipalServices/Views/Receipts/Delete.cshtml
@model MunicipalServices.Data.Receipts

@{
    ViewData["Title"] = "سندات الصرف";
}
<div class="roots-content-wrapper my-4 container-fluid dir-rtl" style="min-height:700px">

    <div class="content-box mt-2">
        <div class="content-box-header">
            <h3 class="content-box__title text-right">حذف</h3>
        </div>
        <div class="content-box-body">
            <div class="content-box-body__row row">
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.FullName)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.FullName)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right">@Html.DisplayNameFor(model => model.AmountOfMoneyNumber)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.AmountOfMoneyNumber)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.AmountOfMoneyText)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.AmountOfMoneyText)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Reason)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Reason)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.OnAccount)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.OnAccount)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.ReceivedFrom)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.ReceivedFrom)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Currency)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Currency)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.CreatedDate)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.CreatedDate)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UpdatedDate)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UpdatedDate)">
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.User)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.User.FullName)">
                </div>
            </div>
        </div>
        <br />
        <div class="root-space__btn-wrapp col-12">
            <form asp-action="Delete">
                <input type="hidden" asp-for="ID" />
                <a asp-action="Index" class="roots-btn btn btn-primary ml-3">إلغاء</a>
                <button type="button" class="roots-btn btn btn-secondary" data-toggle="modal" data-target="#deleteConfirmModal">حذف</button>
            </form>
        </div>
        <br />
    </div>
    </div>

MunicipalServices/Views/Receipts/Details.cshtml
@model MunicipalServices.Data.Receipts

@{
    ViewData["Title"] = "سندات الصرف";
}
<div class="roots-content-wrapper my-4 container-fluid dir-rtl" style="min-height:700px">

    <div class="content-box mt-2">
        <div class="content-box-header">
            <h3 class="content-box__title text-right d-print-none">تفاصيل</h3>
            <h3 class="content-box__title text-right d-none d-print-block">سند صرف - تفاصيل</h3>
        </div>

        <div class="content-box-body">

            <div class="content-box-body__row row">

                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.FullName)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.FullName)">
                </div>

                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right">@Html.DisplayNameFor(model => model.AmountOfMoneyNumber)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.AmountOfMoneyNumber)">
                </div>

                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.AmountOfMoneyText)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.AmountOfMoneyText)">
                </div>

                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Reason)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Reason)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.OnAccount)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.OnAccount)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.ReceivedFrom)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.ReceivedFrom)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Currency)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@MunicipalServices.Helper.Enumerations.GetEnumDescription(Model.Currency)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.CreatedDate)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.CreatedDate)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3 d-print-none">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UpdatedDate)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UpdatedDate)">
                </div>
                <div class="form-item-valid form-group col-6 col-md-3 d-print-none">
                    <label class="input-label text-right"> @Html.DisplayNameFor(model => model.User)</label>
                    <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.User.FullName)">
                </div>
            </div>
        </div>
        <br />
        <div class="root-space__btn-wrapp col-12 d-print-none">
            <a asp-action="Index" class="roots-btn btn btn-secondary ml-3">رجوع</a>
            <a asp-action="Edit" asp-route-id="@Model.ID" class="roots-btn btn btn-primary ml-3">تعديل</a>
            <button onclick="window.print()" class="roots-btn btn btn-primary">طباعة</button>
        </div>
        <br />
    </div>
    <br />
    <div class="card bg-light d-print-none">
        <div class="card-header text-center">الشيكات</div>
        <div class="card-body">
            <p class="text-reset">
                <a asp-action="Create" asp-controller="CashiersChecks" asp-route-id="@Model.ID" asp-route-IsCatchReceipts="false" class="roots-btn btn btn-primary">إضافة جديد</a>
            </p>
            @await Component.InvokeAsync("CashiersChecksList", new { id = Model.ID, IsCatchReceipts = false })
        </div>
    </div>
    <div class="d-none d-print-block">
        <div class="card-header text-center">الشيكات</div>
        <div class="card-body">
            @{
                var model = Model.CashiersChecks.Where(c => c.Deleted == false && c.ReceiptID == Model.ID);
            }
            @Html.Partial("~/Views/CashiersChecks/Index.cshtml", model)
        </div>
    </div>

</div>

MunicipalServices/Views/Receipts/Edit.cshtml
@model MunicipalServices.Data.Receipts

@{
    ViewData["Title"] = "سندات الصرف";
}
<div class="roots-content-wrapper my-4 container-fluid dir-rtl" style="min-height:700px">

    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="content-box mt-2">
            <div class="content-box-header">
                <h3 class="content-box__title text-right">تعديل</h3>
            </div>
            <div class="content-box-body">
                <div class="content-box-body__row row">
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="FullName" class="input-label text-right"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="AmountOfMoneyNumber" class="input-label text-right"></label>
                        <input asp-for="AmountOfMoneyNumber" class="form-control" />
                        <span asp-validation-for="AmountOfMoneyNumber" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="AmountOfMoneyText" class="input-label text-right"></label>
                        <input asp-for="AmountOfMoneyText" class="form-control" />
                        <span asp-validation-for="AmountOfMoneyText" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="Reason" class="input-label text-right"></label>
                        <input asp-for="Reason" class="form-control" />
                        <span asp-validation-for="Reason" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="OnAccount" class="input-label text-right"></label>
                        <input asp-for="OnAccount" class="form-control" />
                        <span asp-validation-for="OnAccount" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="ReceivedFrom" class="input-label text-right"></label>
                        <input asp-for="ReceivedFrom" class="form-control" />
                        <span asp-validation-for="ReceivedFrom" class="text-danger"></span>
                    </div>
                    <div class="form-item-valid form-group col-12 col-md-6">
                        <label asp-for="Currency" class="input-label text-right"></label>
                        <select asp-for="Currency" asp-items="ViewBag.CurrencyType" class="form-control"></select>
                        <span asp-validation-for="Currency" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="root-space__btn-wrapp col-12">
                <a asp-action="Index" class="roots-btn btn btn-secondary ml-3">إلغاء</a>
                <button type="submit" class="roots-btn btn btn-primary roots-btn-w-plus">حفظ</button>
            </div>
            <br />
        </div>
    </form>
        </div>