MunicipalServices/Controllers/ConstructionDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MunicipalServices.Data;

namespace MunicipalServices.Controllers
{
    [Authorize(Roles = "قسم الهندسة,الادارة")]
    public class ConstructionDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Users> _userManager;

        public ConstructionDetailsController(ApplicationDbContext context, UserManager<Users> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ConstructionDetails
        public ViewResult Index()
        {
            var applicationDbContext = _context.ConstructionDetails.Include(c => c.ConstructionLicense).Include(c => c.User).Where(c => c.Deleted == false);
            return View(applicationDbContext);
        }

        // GET: ConstructionDetails/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails
                .Include(c => c.ConstructionLicense)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionDetails == null)
            {
                return NotFound();
            }

            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Create
        public IActionResult Create(Guid id)
        {
            var model = new ConstructionDetails();
            model.ConstructionLicenseID = id;
            return View(model);
        }

        // POST: ConstructionDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConstructionLicenseID,ConstructionDescription,Amount,MeasruingUnit,UnitPrice,Total,ID,CreatedDate,UpdatedDate,UserID,Deleted")] ConstructionDetails constructionDetails)
        {
            if (ModelState.IsValid)
            {
                var dateTime = DateTime.UtcNow;
                constructionDetails.ID = Guid.NewGuid();
                constructionDetails.CreatedDate = dateTime;
                constructionDetails.UpdatedDate = dateTime;
                constructionDetails.Total = constructionDetails.Amount * constructionDetails.UnitPrice;
                constructionDetails.UserID = _userManager.GetUserId(User);
                _context.Add(constructionDetails);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                {
                    if (constructionDetails.ConstructionLicenseID != null)
                    {
                        return RedirectToAction(nameof(Details), nameof(Data.ConstructionLicense) + "s", new { id = constructionDetails.ConstructionLicenseID });
                    }
                }
            }
            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails.FindAsync(id);
            if (constructionDetails == null)
            {
                return NotFound();
            }
            ViewData["ConstructionLicenseID"] = new SelectList(_context.ConstructionLicense, "ID", "ID", constructionDetails.ConstructionLicenseID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", constructionDetails.UserID);
            return View(constructionDetails);
        }

        // POST: ConstructionDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ConstructionLicenseID,ConstructionDescription,Amount,MeasruingUnit,UnitPrice,Total,ID,CreatedDate,UpdatedDate,UserID,Deleted")] ConstructionDetails constructionDetails)
        {
            if (id != constructionDetails.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    constructionDetails.UpdatedDate = DateTime.UtcNow;
                    constructionDetails.Total = constructionDetails.Amount * constructionDetails.UnitPrice;
                    _context.Update(constructionDetails);
                    var result = await _context.SaveChangesAsync();
                    if (result > 0)
                    {
                        if (constructionDetails.ConstructionLicenseID != null)
                        {
                            return RedirectToAction(nameof(Details), nameof(Data.ConstructionLicense) + "s", new { id = constructionDetails.ConstructionLicenseID });
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConstructionDetailsExists(constructionDetails.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["ConstructionLicenseID"] = new SelectList(_context.ConstructionLicense, "ID", "ID", constructionDetails.ConstructionLicenseID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", constructionDetails.UserID);
            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails
                .Include(c => c.ConstructionLicense)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionDetails == null)
            {
                return NotFound();
            }

            return View(constructionDetails);
        }

        // POST: ConstructionDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var constructionDetails = await _context.ConstructionDetails.FindAsync(id);
            constructionDetails.Deleted = true;
            _context.ConstructionDetails.Update(constructionDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConstructionDetailsExists(Guid id)
        {
            return _context.ConstructionDetails.Any(e => e.ID == id);
        }
    }
}

MunicipalServices/Controllers/ConstructionLicensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MunicipalServices.Data;

namespace MunicipalServices.Controllers
{
    [Authorize(Roles = "قسم الهندسة,الادارة")]
    public class ConstructionLicensesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Data.Users> _userManager;

        public ConstructionLicensesController(ApplicationDbContext context, UserManager<Data.Users> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: ConstructionLicenses
        public ViewResult Index()
        {
            var applicationDbContext = _context.ConstructionLicense.Include(c => c.User).Where(c=>c.Deleted == false);
            return View(applicationDbContext);
        }

        // GET: ConstructionLicenses/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionLicense = await _context.ConstructionLicense
                .Include(c => c.LicenseHolderInformation)
                .Include(c => c.User).Include(c=>c.ConstructionDetails)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionLicense == null)
            {
                return NotFound();
            }

            return View(constructionLicense);
        }

        // GET: ConstructionLicenses/Create
        public IActionResult Create()
        {
            ViewData["ConstructionLicenseType"] = new SelectList(from ConstructionLicenseType d in Enum.GetValues(typeof(ConstructionLicenseType)) select new { ID = (int)d, Name = Helper.Enumerations.GetEnumDescription(d) }, "ID", "Name");
            ViewData["BillOfFeesID"] = new SelectList(_context.CatchReceipts, "ID", "FullName");
            ViewData["BillRemainingFeesID"] = new SelectList(_context.CatchReceipts, "ID", "FullName");
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id");
            var model = new ConstructionLicense();
            model.LicenseHolderInformation = new LicenseHolderInformation();
            return View(model);
        }

        // POST: ConstructionLicenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateOfIssuance,FileNumber,ValidatedBySessionNumber,TownName,District,Street,Basin,Part,ConstructionUse,ConstructionLicenseType,LicenseHolderInformation,LocalCommitteeNumber,DateApprovalLocalCommittee,LicenseDescription,LicenseConditions,FeeDate,RemainingFeesDate,BillOfFeesID,BillRemainingFeesID")] ConstructionLicense constructionLicense)
        {
            if (ModelState.IsValid)
            {
                var dateTime = DateTime.UtcNow;
                constructionLicense.ID = Guid.NewGuid();
                constructionLicense.CreatedDate = dateTime;
                constructionLicense.UpdatedDate = dateTime;
                constructionLicense.UserID = _userManager.GetUserId(User);
                constructionLicense.LicenseHolderInformation.ConstructionLicenseID = constructionLicense.ID;
                constructionLicense.LicenseHolderInformation.CreatedDate = dateTime;
                constructionLicense.LicenseHolderInformation.UpdatedDate = dateTime;
                constructionLicense.LicenseHolderInformation.UserID = _userManager.GetUserId(User);

                _context.Add(constructionLicense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(constructionLicense);
        }

        // GET: ConstructionLicenses/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionLicense = await _context.ConstructionLicense.Include(c => c.LicenseHolderInformation).Where(c=>c.ID == id).SingleOrDefaultAsync();
            if (constructionLicense == null)
            {
                return NotFound();
            }
            ViewData["ConstructionLicenseType"] = new SelectList(from ConstructionLicenseType d in Enum.GetValues(typeof(ConstructionLicenseType)) select new { ID = (int)d, Name = Helper.Enumerations.GetEnumDescription(d) }, "ID", "Name");
            ViewData["BillOfFeesID"] = new SelectList(_context.CatchReceipts, "ID", "FullName", constructionLicense.BillOfFeesID);
            ViewData["BillRemainingFeesID"] = new SelectList(_context.CatchReceipts, "ID", "FullName", constructionLicense.BillRemainingFeesID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", constructionLicense.UserID);
            return View(constructionLicense);
        }

        // POST: ConstructionLicenses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("DateOfIssuance,FileNumber,ValidatedBySessionNumber,TownName,District,Street,Basin,Part,ConstructionUse,ConstructionLicenseType,LicenseHolderInformation,LocalCommitteeNumber,DateApprovalLocalCommittee,LicenseDescription,LicenseConditions,FeeDate,RemainingFeesDate,BillOfFeesID,BillRemainingFeesID,ID,CreatedDate,UserID")] ConstructionLicense constructionLicense)
        {
            if (id != constructionLicense.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    constructionLicense.UpdatedDate = DateTime.UtcNow;

                    _context.Update(constructionLicense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConstructionLicenseExists(constructionLicense.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(constructionLicense);
        }

        // GET: ConstructionLicenses/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionLicense = await _context.ConstructionLicense
                .Include(c => c.LicenseHolderInformation)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionLicense == null)
            {
                return NotFound();
            }

            return View(constructionLicense);
        }

        // POST: ConstructionLicenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var constructionLicense = await _context.ConstructionLicense.FindAsync(id);
            constructionLicense.Deleted = true;
            _context.ConstructionLicense.Update(constructionLicense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConstructionLicenseExists(Guid id)
        {
            return _context.ConstructionLicense.Any(e => e.ID == id);
        }
    }
}

MunicipalServices/Views/ConstructionDetails/Create.cshtml
@model MunicipalServices.Data.ConstructionDetails

@{
    ViewData["Title"] = "تفاصيل البناء";
}

<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ConstructionLicenseID" />
    <div class="content-box mt-2">
        <div class="content-box-header">
            <h3 class="content-box__title text-right">إنشاء جديد</h3>
        </div>

        <div class="content-box-body">
            <div class="content-box-body__row row">
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="ConstructionDescription" class="input-label text-right"></label>
                    <input asp-for="ConstructionDescription" class="form-control" />
                    <span asp-validation-for="ConstructionDescription" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="Amount" class="input-label text-right"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="MeasruingUnit" class="input-label text-right"></label>
                    <input asp-for="MeasruingUnit" class="form-control" />
                    <span asp-validation-for="MeasruingUnit" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="UnitPrice" class="input-label text-right"></label>
                    <input asp-for="UnitPrice" class="form-control" />
                    <span asp-validation-for="UnitPrice" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <div class="root-space__btn-wrapp col-12">
            <a asp-action="details" asp-controller="ConstructionLicenses" asp-route-id="@Model.ConstructionLicenseID" class="roots-btn btn btn-secondary ml-3">إلغاء</a>
            <button type="submit" class="roots-btn btn btn-primary roots-btn-w-plus">إضافة</button>
        </div>
        <br />
    </div>
</form>

MunicipalServices/Views/ConstructionDetails/Delete.cshtml
@model MunicipalServices.Data.ConstructionDetails

@{
    ViewData["Title"] = "تفاصيل البناء";
}

<div class="content-box mt-2">
    <div class="content-box-header">
        <h3 class="content-box__title text-right">حذف</h3>
    </div>
    <div class="content-box-body">
        <div class="content-box-body__row row">
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.ConstructionDescription)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.ConstructionDescription)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right">@Html.DisplayNameFor(model => model.Amount)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Amount)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.MeasruingUnit)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.MeasruingUnit)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UnitPrice)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UnitPrice)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Total)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Total)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.CreatedDate)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.CreatedDate)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UpdatedDate)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UpdatedDate)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.User)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.User.FullName)">
            </div>
        </div>
    </div>
    <br />
    <div class="root-space__btn-wrapp" style="margin-left:15px;">
        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <a asp-action="details" asp-controller="ConstructionLicenses" asp-route-id="@Model.ConstructionLicenseID" class="roots-btn btn btn-primary ml-3">إلغاء</a>
            <button type="button" class="roots-btn btn btn-secondary" data-toggle="modal" data-target="#deleteConfirmModal">حذف</button>
        </form>
    </div>
    <br />
</div>

MunicipalServices/Views/ConstructionDetails/Details.cshtml
@model MunicipalServices.Data.ConstructionDetails

@{
    ViewData["Title"] = "تفاصيل البناء";
}

<div class="content-box mt-2">
    <div class="content-box-header">
        <h3 class="content-box__title text-right">تفاصيل</h3>
    </div>
    <div class="content-box-body">
        <div class="content-box-body__row row">
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.ConstructionDescription)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.ConstructionDescription)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right">@Html.DisplayNameFor(model => model.Amount)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Amount)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.MeasruingUnit)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.MeasruingUnit)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UnitPrice)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UnitPrice)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.Total)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.Total)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6 d-print-none">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.CreatedDate)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.CreatedDate)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.UpdatedDate)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.UpdatedDate)">
            </div>
            <div class="form-item-valid form-group col-12 col-md-6 d-print-none">
                <label class="input-label text-right"> @Html.DisplayNameFor(model => model.User)</label>
                <input class="form-control input" id="inputtext-2" disabled="disabled" value="@Html.DisplayFor(model => model.User.FullName)">
            </div>
        </div>
    </div>
    <br />
    <div class="root-space__btn-wrapp col-12">
        <a asp-action="details" asp-controller="ConstructionLicenses" asp-route-id="@Model.ConstructionLicenseID" class="roots-btn btn btn-secondary ml-3">رجوع</a>
        <a asp-action="Edit" asp-route-id="@Model.ID" class="roots-btn btn btn-primary">تعديل</a>
    </div>
    <br />
</div>

MunicipalServices/Views/ConstructionDetails/Edit.cshtml
@model MunicipalServices.Data.ConstructionDetails

@{
    ViewData["Title"] = "تفاصيل البناء";
}

<form asp-action="Edit" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="content-box mt-2">
        <div class="content-box-header">
            <h3 class="content-box__title text-right">تعديل</h3>
        </div>
        <div class="content-box-body">
            <div class="content-box-body__row row">
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="ConstructionDescription" class="input-label text-right"></label>
                    <input asp-for="ConstructionDescription" class="form-control" />
                    <span asp-validation-for="ConstructionDescription" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="Amount" class="input-label text-right"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="MeasruingUnit" class="input-label text-right"></label>
                    <input asp-for="MeasruingUnit" class="form-control" />
                    <span asp-validation-for="MeasruingUnit" class="text-danger"></span>
                </div>
                <div class="form-item-valid form-group col-12 col-md-6">
                    <label asp-for="UnitPrice" class="input-label text-right"></label>
                    <input asp-for="UnitPrice" class="form-control" />
                    <span asp-validation-for="UnitPrice" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <div class="root-space__btn-wrapp col-12">
            <a asp-action="details" asp-controller="ConstructionLicenses" asp-route-id="@Model.ConstructionLicenseID" class="roots-btn btn btn-secondary ml-3">إلغاء</a>
            <button type="submit" class="roots-btn btn btn-primary roots-btn-w-plus">حفظ</button>
        </div>
        <br />
    </div>
</form>

MunicipalServices/Views/ConstructionDetails/Index.cshtml
@model IEnumerable<MunicipalServices.Data.ConstructionDetails>

@{
    ViewData["Title"] = "Index";
}

<div class="roots-content-wrapper my-4 container-fluid dir-rtl" style="min-height:700px">
    <table class="roots-table table borderless" cellspacing="0">
        <thead>
            <tr class="table-row-thead text-right">
                <th scope="col">@Html.DisplayNameFor(model => model.ConstructionDescription)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Amount)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.MeasruingUnit)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.UnitPrice)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Total)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-row-item text-right">
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.ConstructionDescription)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.Amount)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.MeasruingUnit)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.UnitPrice)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.Total)</td>
                    <td class="table-text"></td>
                </tr>
            }
        </tbody>
    </table>
</div>