MunicipalServices/Controllers/ConstructionDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MunicipalServices.Data;

namespace MunicipalServices.Controllers
{
    [Authorize(Roles = "قسم الهندسة,الادارة")]
    public class ConstructionDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Users> _userManager;

        public ConstructionDetailsController(ApplicationDbContext context, UserManager<Users> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ConstructionDetails
        public ViewResult Index()
        {
            var applicationDbContext = _context.ConstructionDetails.Include(c => c.ConstructionLicense).Include(c => c.User).Where(c => c.Deleted == false);
            return View(applicationDbContext);
        }

        // GET: ConstructionDetails/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails
                .Include(c => c.ConstructionLicense)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionDetails == null)
            {
                return NotFound();
            }

            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Create
        public IActionResult Create(Guid id)
        {
            var model = new ConstructionDetails();
            model.ConstructionLicenseID = id;
            return View(model);
        }

        // POST: ConstructionDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConstructionLicenseID,ConstructionDescription,Amount,MeasruingUnit,UnitPrice,Total,ID,CreatedDate,UpdatedDate,UserID,Deleted")] ConstructionDetails constructionDetails)
        {
            if (ModelState.IsValid)
            {
                var dateTime = DateTime.UtcNow;
                constructionDetails.ID = Guid.NewGuid();
                constructionDetails.CreatedDate = dateTime;
                constructionDetails.UpdatedDate = dateTime;
                constructionDetails.Total = constructionDetails.Amount * constructionDetails.UnitPrice;
                constructionDetails.UserID = _userManager.GetUserId(User);
                _context.Add(constructionDetails);
                var result = await _context.SaveChangesAsync();
                if (result > 0)
                {
                    if (constructionDetails.ConstructionLicenseID != null)
                    {
                        return RedirectToAction(nameof(Details), nameof(Data.ConstructionLicense) + "s", new { id = constructionDetails.ConstructionLicenseID });
                    }
                }
            }
            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails.FindAsync(id);
            if (constructionDetails == null)
            {
                return NotFound();
            }
            ViewData["ConstructionLicenseID"] = new SelectList(_context.ConstructionLicense, "ID", "ID", constructionDetails.ConstructionLicenseID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", constructionDetails.UserID);
            return View(constructionDetails);
        }

        // POST: ConstructionDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ConstructionLicenseID,ConstructionDescription,Amount,MeasruingUnit,UnitPrice,Total,ID,CreatedDate,UpdatedDate,UserID,Deleted")] ConstructionDetails constructionDetails)
        {
            if (id != constructionDetails.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    constructionDetails.UpdatedDate = DateTime.UtcNow;
                    constructionDetails.Total = constructionDetails.Amount * constructionDetails.UnitPrice;
                    _context.Update(constructionDetails);
                    var result = await _context.SaveChangesAsync();
                    if (result > 0)
                    {
                        if (constructionDetails.ConstructionLicenseID != null)
                        {
                            return RedirectToAction(nameof(Details), nameof(Data.ConstructionLicense) + "s", new { id = constructionDetails.ConstructionLicenseID });
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConstructionDetailsExists(constructionDetails.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["ConstructionLicenseID"] = new SelectList(_context.ConstructionLicense, "ID", "ID", constructionDetails.ConstructionLicenseID);
            ViewData["UserID"] = new SelectList(_context.Users, "Id", "Id", constructionDetails.UserID);
            return View(constructionDetails);
        }

        // GET: ConstructionDetails/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var constructionDetails = await _context.ConstructionDetails
                .Include(c => c.ConstructionLicense)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (constructionDetails == null)
            {
                return NotFound();
            }

            return View(constructionDetails);
        }

        // POST: ConstructionDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var constructionDetails = await _context.ConstructionDetails.FindAsync(id);
            constructionDetails.Deleted = true;
            _context.ConstructionDetails.Update(constructionDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConstructionDetailsExists(Guid id)
        {
            return _context.ConstructionDetails.Any(e => e.ID == id);
        }
    }
}

MunicipalServices/Views/Shared/Components/ConstructionDetailsList/Default.cshtml
@model IQueryable<MunicipalServices.Data.ConstructionDetails>

@{
    ViewData["Title"] = "تفاصيل البناء";
}

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add().RenderedAs((model, row) => row + 1).Titled("#").Css("text-center");
        columns.Add(model => model.ConstructionDescription).Titled("وصف البناء");
        columns.Add(model => model.Amount).Titled("الكمية");
        columns.Add(model => model.MeasruingUnit).Titled("وحدة القياس");
        columns.Add(model => model.UnitPrice).Titled("سعر الوحدة");
        columns.Add(model => model.Total).Titled("المجموع");
        columns.Add(model => model.CreatedDate).Titled("تاريخ الإنشاء");
        columns.Add(model => model.UpdatedDate).Titled("اخر تعديل");
        columns.Add(model => model.User.FullName).Titled("تم بواسطة");
        columns.Add(model => $"<div class=\"dropdown\">" +
        $"<button class=\"table-dropdow-btn btn\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">...</button>" +
        $"<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownmenubutton\">" +
        $"<a class=\"dropdown-item\" href=\"ConstructionDetails/edit/{model.ID}\">تعديل</a>" +
        $"<a class=\"dropdown-item\" href=\"ConstructionDetails/details/{model.ID}\">تفاصيل</a>" +
        $"<a class=\"dropdown-item\" href=\"ConstructionDetails/delete/{model.ID}\">حذف</a>" +
        $"</div></div>").Encoded(false);
    })
    .Using(GridFilterMode.Row)
    .Empty("لا يوجد بيانات حاليا")
    .Filterable()
    .Sortable()
    .Pageable()
)

@*<div class="table-responsive">
    <table class="roots-table table borderless" cellspacing="0">
        <thead>
            <tr class="table-row-thead">
                <th scope="col">@Html.DisplayNameFor(model => model.ConstructionDescription)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Amount)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.MeasruingUnit)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.UnitPrice)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Total)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.UpdatedDate)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.CreatedDate)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.User)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-row-item">
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.ConstructionDescription)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.Amount)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.MeasruingUnit)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.UnitPrice)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.Total)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.UpdatedDate)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.CreatedDate)</td>
                    <td class="table-bold-text">@Html.DisplayFor(modelItem => item.User.FullName)</td>
                    <td class="table-text table-product-more-btn">
                        <div class="dropdown">
                            <button class="table-dropdow-btn btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">...</button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownmenubutton">
                                <a class="dropdown-item" asp-action="edit" asp-controller="ConstructionDetails" asp-route-id="@item.ID">Edit</a>
                                <a class="dropdown-item" asp-action="details" asp-controller="ConstructionDetails" asp-route-id="@item.ID">Details</a>
                                <a class="dropdown-item" asp-action="delete" asp-controller="ConstructionDetails" asp-route-id="@item.ID">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>*@